use StoreKeeper

create table #Orders
(
	[Priority] int not null,
	Code nvarchar(100) not null,
	[Count] float not null
)



--select 
--	'insert into #Orders ([Priority], Code, [Count]) values (' + cast(po.Priority as nvarchar(10)) + ', ''' + a.Code + ''', ' + cast(po.Count as nvarchar(20)) + ')' as [Sql]
--from
--	ProductArticleOrders po
--	join ProductArticles pa on (pa.Id = po.ProductArticleId) 
--	join Articles a on (a.Id = pa.ArticleId)
--order by po.Priority

insert into #Orders ([Priority], Code, [Count]) values (1, '1247887', 50)
insert into #Orders ([Priority], Code, [Count]) values (2, '1247888-1', 50)
insert into #Orders ([Priority], Code, [Count]) values (3, 'ALF NEON', 0)
insert into #Orders ([Priority], Code, [Count]) values (4, 'ALF-01', 90)
insert into #Orders ([Priority], Code, [Count]) values (5, 'ALF-02', 97)
insert into #Orders ([Priority], Code, [Count]) values (6, 'CAT1', 0)
insert into #Orders ([Priority], Code, [Count]) values (7, 'CAT2TX', 0)
insert into #Orders ([Priority], Code, [Count]) values (8, 'DBX-093', 28)
insert into #Orders ([Priority], Code, [Count]) values (9, 'DBX-093T', 28)
insert into #Orders ([Priority], Code, [Count]) values (10, 'DBX-093R', 28)
insert into #Orders ([Priority], Code, [Count]) values (11, 'DBX-094', 5)
insert into #Orders ([Priority], Code, [Count]) values (12, 'DBX-094T', 5)
insert into #Orders ([Priority], Code, [Count]) values (13, 'DBX-094R', 5)
insert into #Orders ([Priority], Code, [Count]) values (14, 'e1B', 0)
insert into #Orders ([Priority], Code, [Count]) values (15, 'e1G', 0)
insert into #Orders ([Priority], Code, [Count]) values (16, 'e1R', 0)
insert into #Orders ([Priority], Code, [Count]) values (17, 'e1Y', 0)
insert into #Orders ([Priority], Code, [Count]) values (18, 'NEON RFL1', 0)
insert into #Orders ([Priority], Code, [Count]) values (19, 'NEON RFL2', 0)
insert into #Orders ([Priority], Code, [Count]) values (20, 'RFL3', 0)
insert into #Orders ([Priority], Code, [Count]) values (21, 'Q-TX2', 0)
insert into #Orders ([Priority], Code, [Count]) values (22, 'NEON RX', 0)
insert into #Orders ([Priority], Code, [Count]) values (23, 'NEON B', 0)
insert into #Orders ([Priority], Code, [Count]) values (24, 'NEON G', 0)
insert into #Orders ([Priority], Code, [Count]) values (25, 'NEON O', 0)
insert into #Orders ([Priority], Code, [Count]) values (26, 'NEON R', 0)
insert into #Orders ([Priority], Code, [Count]) values (27, 'NEON V', 0)
insert into #Orders ([Priority], Code, [Count]) values (28, 'NEON Y', 0)
insert into #Orders ([Priority], Code, [Count]) values (29, 'SAP-01', 15)
insert into #Orders ([Priority], Code, [Count]) values (30, 'Q9B', 0)
insert into #Orders ([Priority], Code, [Count]) values (31, 'Q9G', 0)
insert into #Orders ([Priority], Code, [Count]) values (32, 'Q9R', 0)
insert into #Orders ([Priority], Code, [Count]) values (33, 'Q9Y', 0)
insert into #Orders ([Priority], Code, [Count]) values (34, 'Q9-TXB', 0)
insert into #Orders ([Priority], Code, [Count]) values (35, 'Q9-TXG', 158)
insert into #Orders ([Priority], Code, [Count]) values (36, 'Q9-TXR', 136)
insert into #Orders ([Priority], Code, [Count]) values (37, 'Q9-TXY', 0)
insert into #Orders ([Priority], Code, [Count]) values (38, 'Q-RX2', 204)
insert into #Orders ([Priority], Code, [Count]) values (39, 'Q-SOLAR-TXB', 0)
insert into #Orders ([Priority], Code, [Count]) values (40, 'Q-SOLAR-TXG', 0)
insert into #Orders ([Priority], Code, [Count]) values (41, 'Q-SOLAR-TXR', 0)
insert into #Orders ([Priority], Code, [Count]) values (42, 'Q-SOLAR-TXY', 0)
insert into #Orders ([Priority], Code, [Count]) values (43, '2717', 0)
insert into #Orders ([Priority], Code, [Count]) values (44, '120', 19)
insert into #Orders ([Priority], Code, [Count]) values (45, '121', 21)
insert into #Orders ([Priority], Code, [Count]) values (46, '1629', 0)
insert into #Orders ([Priority], Code, [Count]) values (47, '2720', 28)
insert into #Orders ([Priority], Code, [Count]) values (48, '357', 0)
insert into #Orders ([Priority], Code, [Count]) values (49, '357EXT', 0)
insert into #Orders ([Priority], Code, [Count]) values (50, '453', 0)
insert into #Orders ([Priority], Code, [Count]) values (51, '530C', 0)
insert into #Orders ([Priority], Code, [Count]) values (52, '628B', 0)
insert into #Orders ([Priority], Code, [Count]) values (53, '628BAL6A', 0)
insert into #Orders ([Priority], Code, [Count]) values (54, 'CIM6R', 10)
insert into #Orders ([Priority], Code, [Count]) values (55, 'HTR-9', 27)
insert into #Orders ([Priority], Code, [Count]) values (56, 'KP2RX', 0)
insert into #Orders ([Priority], Code, [Count]) values (57, 'KP4RX', 19)
insert into #Orders ([Priority], Code, [Count]) values (58, 'KP5RX', 0)
insert into #Orders ([Priority], Code, [Count]) values (59, 'ODKAM1', 14)
insert into #Orders ([Priority], Code, [Count]) values (60, 'EGM1', 18)
insert into #Orders ([Priority], Code, [Count]) values (61, 'UGM EV v2 v', 18)
insert into #Orders ([Priority], Code, [Count]) values (62, 'EMA', 0)
insert into #Orders ([Priority], Code, [Count]) values (63, 'EMA-HOME', 46)
insert into #Orders ([Priority], Code, [Count]) values (64, 'EMA-CORD', 0)
insert into #Orders ([Priority], Code, [Count]) values (65, 'EMA-PIR', 0)
insert into #Orders ([Priority], Code, [Count]) values (66, 'F-3TXB', 0)
insert into #Orders ([Priority], Code, [Count]) values (67, 'F-4TX', 0)
insert into #Orders ([Priority], Code, [Count]) values (68, 'F-DIN', 0)
insert into #Orders ([Priority], Code, [Count]) values (69, 'F-DOOR', 0)
insert into #Orders ([Priority], Code, [Count]) values (70, 'F-FLOOD', 57)
insert into #Orders ([Priority], Code, [Count]) values (71, 'F-INPUT', 0)
insert into #Orders ([Priority], Code, [Count]) values (72, 'F-PIR', 0)
insert into #Orders ([Priority], Code, [Count]) values (73, 'F-SCK', 0)
insert into #Orders ([Priority], Code, [Count]) values (74, 'F-SMK', 0)
insert into #Orders ([Priority], Code, [Count]) values (75, 'GSM-CAM2-B', 6)
insert into #Orders ([Priority], Code, [Count]) values (76, 'GSM-CAM2-W', 0)
insert into #Orders ([Priority], Code, [Count]) values (77, 'GSM-DIN3B', 170)
insert into #Orders ([Priority], Code, [Count]) values (78, 'GSM-SCK1-W', 54)
insert into #Orders ([Priority], Code, [Count]) values (79, 'uGATE3A', 25)
insert into #Orders ([Priority], Code, [Count]) values (80, 'uGATE3B', 40)
insert into #Orders ([Priority], Code, [Count]) values (81, 'UGM1', 0)
insert into #Orders ([Priority], Code, [Count]) values (82, 'ETH-BOX1', 0)
insert into #Orders ([Priority], Code, [Count]) values (83, 'KH1RX-SMD', 45)
insert into #Orders ([Priority], Code, [Count]) values (84, 'KH2RX-SMD', 0)
insert into #Orders ([Priority], Code, [Count]) values (85, 'MOP6', 6)
insert into #Orders ([Priority], Code, [Count]) values (86, 'MRX1', 0)
insert into #Orders ([Priority], Code, [Count]) values (87, 'MRX12-SMA', 0)
insert into #Orders ([Priority], Code, [Count]) values (88, 'MRX1-SMA', 0)
insert into #Orders ([Priority], Code, [Count]) values (89, 'MRX6', 15)
insert into #Orders ([Priority], Code, [Count]) values (90, 'MTX1', 25)
insert into #Orders ([Priority], Code, [Count]) values (91, 'MTX1-SMA', 0)
insert into #Orders ([Priority], Code, [Count]) values (92, 'MTX2', 12)
insert into #Orders ([Priority], Code, [Count]) values (93, 'MTX2-SMA', 0)
insert into #Orders ([Priority], Code, [Count]) values (94, 'REM6', 0)
insert into #Orders ([Priority], Code, [Count]) values (95, 'RFID2000', 0)
insert into #Orders ([Priority], Code, [Count]) values (96, 'RFID-PS25', 0)
insert into #Orders ([Priority], Code, [Count]) values (97, 'RPS6F', 0)
insert into #Orders ([Priority], Code, [Count]) values (98, 'RS485', 0)
insert into #Orders ([Priority], Code, [Count]) values (99, 'R-USB1', 68)
insert into #Orders ([Priority], Code, [Count]) values (100, 'RFID125A-USB', 68)
insert into #Orders ([Priority], Code, [Count]) values (101, 'TER6', 0)
insert into #Orders ([Priority], Code, [Count]) values (102, '1338024', 672)
insert into #Orders ([Priority], Code, [Count]) values (103, 'WATTAN B280', 10)
insert into #Orders ([Priority], Code, [Count]) values (104, 'TRC-08', 10)
insert into #Orders ([Priority], Code, [Count]) values (105, '1247884', 128)
insert into #Orders ([Priority], Code, [Count]) values (106, '1247885', 128)
insert into #Orders ([Priority], Code, [Count]) values (107, '1247886', 128)
insert into #Orders ([Priority], Code, [Count]) values (108, '1247887', 100)
insert into #Orders ([Priority], Code, [Count]) values (109, '1247888-1', 100)
insert into #Orders ([Priority], Code, [Count]) values (110, '1294330', 128)
insert into #Orders ([Priority], Code, [Count]) values (111, '1294332', 250)

begin tran
insert into ProductArticleOrders (Id, ProductArticleId, [Count], [Priority], ProductionCount)
select NEWID(), pa.Id, o.[Count], o.[Priority], 0
from
	#Orders o
	join Articles a on (a.Code = o.Code)
	join ProductArticles pa on (pa.ArticleId = a.Id)
	
select * from ProductArticleOrders order by [Priority]

commit

drop table #Orders